[versions]
lombok = "1.18.36"
junit = "5.10.0"
assertj = "3.24.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj"}
